### ISSUE TITLE
$rfs-breakpoint, height and width.

### ISSUE THREAD

**Issue by marcoribeiroweb** [project-rfs/rfs#19]
Hi, first of all, thank you for your work. 👍

I have a question, i set the $rfs-two-dimensional true to enable the two dimensional media queries in height, but i need an $rfs-breakpoint for screen height aswell, to block the maximum font size, like i can do with $rfs-breakpoint for screen width. 

EDITED: I need different sizes for width and height (example 1440 por width and 1024 for height). 

Is there a way to do that?

Thank you in advance.

**Comment by MartijnCuppens** [comment]
Hi @marcoribeiroweb,

Thanks for the appreciation!

The idea behind `$rfs-two-dimensional ` is that the font-size doesn't change on the mobile devices if the orientation is changed. I disable this by default because it's easier to understand what's going on when the font size is bound only to the screen width.

When configuring RFS, you have the choice between one of these options:
- You bind the font resizing to the width of the screen (`$rfs-two-dimensional: false;`)
- You bind the font resizing to the smallest side of the screen (`$rfs-two-dimensional: true;`)

It doesn't matter which option your chose, you will always have 2 scenarios:
- The screen is wider than the breakpoint
- The screen is smaller than the breakpoint

So what you 're trying to do isn't possible right now.

If we're going to change this behaviour and we need to take check the font-size based on a screen width and a screen height, stuff will become a bit more complex because we can have 4 scenarios:
- The screen is smaller than the width breakpoint and smaller than the height breakpoint
- The screen is wider than the width breakpoint and smaller than the height breakpoint
- The screen is smaller than the width breakpoint and wider than the height breakpoint
- The screen is wider than the width breakpoint and wider than the height breakpoint

This means the code will become a bit more complex and 2 extra media queries will be generated for each font size. I personally think this won't be a good idea.

**Comment by marcoribeiroweb** [comment]
Hi @MartijnCuppens.
Thank you for your fast response!
I completely understand your explanation. Im going to think other way to do what i need.
Thank you, cheers. 👍
